apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: react-app
  template:
    metadata:
      name: react-app
      labels:
        name: react-app
    spec:
      containers:
       - name: react-app
         image: 642733809371.dkr.ecr.us-east-1.amazonaws.com/react-app:latest
         resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
         ports:
          - containerPort: 80

# service for deployment
---
apiVersion: v1
kind: Service
metadata:
  name: reactap-service
spec:
  type: LoadBalancer
  selector:
    name: reactapp
  ports:
  - port: 8080
    targetPort: 80